import pandas as pd
import numpy as np


def ma_crossover_signal(df, fast=20, slow=50):
    """
    Moving average crossover signal.

    Logic:
        When fast SMA crosses above slow SMA -> buy signal (1)
        When fast SMA crosses below slow SMA -> sell signal (-1)
        Otherwise -> flat (0)

    CRITICAL: Signal is shifted by 1 day to avoid look-ahead bias.
    The signal generated by today's prices executes at tomorrow's open.
    Without this shift, we would be using future information.

    Args:
        df: DataFrame with sma_{fast} and sma_{slow} columns
        fast: fast moving average window
        slow: slow moving average window

    Returns:
        pandas Series of signals (-1, 0, 1)
    """
    # Verify required columns exist
    assert f'sma_{fast}' in df.columns, f"sma_{fast} not found — run add_moving_averages first"
    assert f'sma_{slow}' in df.columns, f"sma_{slow} not found — run add_moving_averages first"

    signal = pd.Series(0, index=df.index, name='signal')
    signal[df[f'sma_{fast}'] > df[f'sma_{slow}']] = 1
    signal[df[f'sma_{fast}'] < df[f'sma_{slow}']] = -1

    # Shift by 1 to avoid look-ahead bias
    # Today's signal is generated after market close
    # and executed at the following day's open
    signal = signal.shift(1)

    return signal

def ma_crossover_long_only(df, fast=20, slow=50):
    """
    Long-only version of MA crossover.
    Goes long when fast SMA > slow SMA, flat otherwise.
    Never takes short positions.
    
    This is more appropriate for a strongly trending asset
    like SPY where shorting during a bull market is costly.
    
    Signal: 1 = long, 0 = flat (cash)
    """
    assert f'sma_{fast}' in df.columns
    assert f'sma_{slow}' in df.columns

    signal = pd.Series(0, index=df.index, name='signal')
    signal[df[f'sma_{fast}'] > df[f'sma_{slow}']] = 1

    # Shift to avoid look-ahead bias
    return signal.shift(1)


def signal_summary(signal):
    """
    Print a summary of signal distribution.
    Useful sanity check — signals should not be overwhelmingly
    one-sided, which would suggest a bug.
    """
    counts = signal.value_counts()
    total = len(signal.dropna())
    print("\nSignal Distribution:")
    print(f"  Long  (+1): {counts.get(1.0, 0)} days ({counts.get(1.0, 0)/total*100:.1f}%)")
    print(f"  Flat   (0): {counts.get(0.0, 0)} days ({counts.get(0.0, 0)/total*100:.1f}%)")
    print(f"  Short (-1): {counts.get(-1.0, 0)} days ({counts.get(-1.0, 0)/total*100:.1f}%)")
    print(f"  Total     : {total} days")